<?php
// automatically generated by the FlatBuffers compiler, do not modify

namespace optional_scalars;

class OptionalByte
{
    const None = 0;
    const One = 1;
    const Two = 2;

    private static $names = array(
        OptionalByte::None=>"None",
        OptionalByte::One=>"One",
        OptionalByte::Two=>"Two",
    );

    public static function Name($e)
    {
        if (!isset(self::$names[$e])) {
            throw new \Exception();
        }
        return self::$names[$e];
    }
}
