<?php
// automatically generated by the FlatBuffers compiler, do not modify

namespace optional_scalars;

use \Google\FlatBuffers\Struct;
use \Google\FlatBuffers\Table;
use \Google\FlatBuffers\ByteBuffer;
use \Google\FlatBuffers\FlatBufferBuilder;
use \Google\FlatBuffers\Constants;

class ScalarStuff extends Table
{
    /**
     * @param ByteBuffer $bb
     * @return ScalarStuff
     */
    public static function getRootAsScalarStuff(ByteBuffer $bb)
    {
        $obj = new ScalarStuff();
        return $obj->init($bb->getInt($bb->getPosition()) + $bb->getPosition(), $bb);
    }

    /**
     * @param ByteBuffer $bb
     * @return ScalarStuff
     */
    public static function getSizePrefixedRootAsScalarStuff(ByteBuffer $bb)
    {
        $obj = new ScalarStuff();
        $bb->setPosition($bb->getPosition() + Constants::SIZEOF_INT);
        return $obj->init($bb->getInt($bb->getPosition()) + $bb->getPosition(), $bb);
    }

    public static function ScalarStuffIdentifier()
    {
        return "NULL";
    }

    public static function ScalarStuffBufferHasIdentifier(ByteBuffer $buf)
    {
        return self::__has_identifier($buf, self::ScalarStuffIdentifier());
    }

    public static function ScalarStuffExtension()
    {
        return "mon";
    }

    /**
     * @param int $_i offset
     * @param ByteBuffer $_bb
     * @return ScalarStuff
     **/
    public function init($_i, ByteBuffer $_bb)
    {
        $this->bb_pos = $_i;
        $this->bb = $_bb;
        return $this;
    }

    /**
     * @return sbyte
     */
    public function getJustI8()
    {
        $o = $this->__offset(4);
        return $o != 0 ? $this->bb->getSbyte($o + $this->bb_pos) : 0;
    }

    /**
     * @return ?sbyte
     */
    public function getMaybeI8()
    {
        $o = $this->__offset(6);
        return $o != 0 ? $this->bb->getSbyte($o + $this->bb_pos) : null;
    }

    /**
     * @return sbyte
     */
    public function getDefaultI8()
    {
        $o = $this->__offset(8);
        return $o != 0 ? $this->bb->getSbyte($o + $this->bb_pos) : 42;
    }

    /**
     * @return byte
     */
    public function getJustU8()
    {
        $o = $this->__offset(10);
        return $o != 0 ? $this->bb->getByte($o + $this->bb_pos) : 0;
    }

    /**
     * @return ?byte
     */
    public function getMaybeU8()
    {
        $o = $this->__offset(12);
        return $o != 0 ? $this->bb->getByte($o + $this->bb_pos) : null;
    }

    /**
     * @return byte
     */
    public function getDefaultU8()
    {
        $o = $this->__offset(14);
        return $o != 0 ? $this->bb->getByte($o + $this->bb_pos) : 42;
    }

    /**
     * @return short
     */
    public function getJustI16()
    {
        $o = $this->__offset(16);
        return $o != 0 ? $this->bb->getShort($o + $this->bb_pos) : 0;
    }

    /**
     * @return ?short
     */
    public function getMaybeI16()
    {
        $o = $this->__offset(18);
        return $o != 0 ? $this->bb->getShort($o + $this->bb_pos) : null;
    }

    /**
     * @return short
     */
    public function getDefaultI16()
    {
        $o = $this->__offset(20);
        return $o != 0 ? $this->bb->getShort($o + $this->bb_pos) : 42;
    }

    /**
     * @return ushort
     */
    public function getJustU16()
    {
        $o = $this->__offset(22);
        return $o != 0 ? $this->bb->getUshort($o + $this->bb_pos) : 0;
    }

    /**
     * @return ?ushort
     */
    public function getMaybeU16()
    {
        $o = $this->__offset(24);
        return $o != 0 ? $this->bb->getUshort($o + $this->bb_pos) : null;
    }

    /**
     * @return ushort
     */
    public function getDefaultU16()
    {
        $o = $this->__offset(26);
        return $o != 0 ? $this->bb->getUshort($o + $this->bb_pos) : 42;
    }

    /**
     * @return int
     */
    public function getJustI32()
    {
        $o = $this->__offset(28);
        return $o != 0 ? $this->bb->getInt($o + $this->bb_pos) : 0;
    }

    /**
     * @return ?int
     */
    public function getMaybeI32()
    {
        $o = $this->__offset(30);
        return $o != 0 ? $this->bb->getInt($o + $this->bb_pos) : null;
    }

    /**
     * @return int
     */
    public function getDefaultI32()
    {
        $o = $this->__offset(32);
        return $o != 0 ? $this->bb->getInt($o + $this->bb_pos) : 42;
    }

    /**
     * @return uint
     */
    public function getJustU32()
    {
        $o = $this->__offset(34);
        return $o != 0 ? $this->bb->getUint($o + $this->bb_pos) : 0;
    }

    /**
     * @return ?uint
     */
    public function getMaybeU32()
    {
        $o = $this->__offset(36);
        return $o != 0 ? $this->bb->getUint($o + $this->bb_pos) : null;
    }

    /**
     * @return uint
     */
    public function getDefaultU32()
    {
        $o = $this->__offset(38);
        return $o != 0 ? $this->bb->getUint($o + $this->bb_pos) : 42;
    }

    /**
     * @return long
     */
    public function getJustI64()
    {
        $o = $this->__offset(40);
        return $o != 0 ? $this->bb->getLong($o + $this->bb_pos) : 0;
    }

    /**
     * @return ?long
     */
    public function getMaybeI64()
    {
        $o = $this->__offset(42);
        return $o != 0 ? $this->bb->getLong($o + $this->bb_pos) : null;
    }

    /**
     * @return long
     */
    public function getDefaultI64()
    {
        $o = $this->__offset(44);
        return $o != 0 ? $this->bb->getLong($o + $this->bb_pos) : 42;
    }

    /**
     * @return ulong
     */
    public function getJustU64()
    {
        $o = $this->__offset(46);
        return $o != 0 ? $this->bb->getUlong($o + $this->bb_pos) : 0;
    }

    /**
     * @return ?ulong
     */
    public function getMaybeU64()
    {
        $o = $this->__offset(48);
        return $o != 0 ? $this->bb->getUlong($o + $this->bb_pos) : null;
    }

    /**
     * @return ulong
     */
    public function getDefaultU64()
    {
        $o = $this->__offset(50);
        return $o != 0 ? $this->bb->getUlong($o + $this->bb_pos) : 42;
    }

    /**
     * @return float
     */
    public function getJustF32()
    {
        $o = $this->__offset(52);
        return $o != 0 ? $this->bb->getFloat($o + $this->bb_pos) : 0.0;
    }

    /**
     * @return ?float
     */
    public function getMaybeF32()
    {
        $o = $this->__offset(54);
        return $o != 0 ? $this->bb->getFloat($o + $this->bb_pos) : null;
    }

    /**
     * @return float
     */
    public function getDefaultF32()
    {
        $o = $this->__offset(56);
        return $o != 0 ? $this->bb->getFloat($o + $this->bb_pos) : 42.0;
    }

    /**
     * @return double
     */
    public function getJustF64()
    {
        $o = $this->__offset(58);
        return $o != 0 ? $this->bb->getDouble($o + $this->bb_pos) : 0.0;
    }

    /**
     * @return ?double
     */
    public function getMaybeF64()
    {
        $o = $this->__offset(60);
        return $o != 0 ? $this->bb->getDouble($o + $this->bb_pos) : null;
    }

    /**
     * @return double
     */
    public function getDefaultF64()
    {
        $o = $this->__offset(62);
        return $o != 0 ? $this->bb->getDouble($o + $this->bb_pos) : 42.0;
    }

    /**
     * @return bool
     */
    public function getJustBool()
    {
        $o = $this->__offset(64);
        return $o != 0 ? $this->bb->getBool($o + $this->bb_pos) : false;
    }

    /**
     * @return ?bool
     */
    public function getMaybeBool()
    {
        $o = $this->__offset(66);
        return $o != 0 ? $this->bb->getBool($o + $this->bb_pos) : null;
    }

    /**
     * @return bool
     */
    public function getDefaultBool()
    {
        $o = $this->__offset(68);
        return $o != 0 ? $this->bb->getBool($o + $this->bb_pos) : true;
    }

    /**
     * @return sbyte
     */
    public function getJustEnum()
    {
        $o = $this->__offset(70);
        return $o != 0 ? $this->bb->getSbyte($o + $this->bb_pos) : \optional_scalars\OptionalByte::None;
    }

    /**
     * @return ?sbyte
     */
    public function getMaybeEnum()
    {
        $o = $this->__offset(72);
        return $o != 0 ? $this->bb->getSbyte($o + $this->bb_pos) : null;
    }

    /**
     * @return sbyte
     */
    public function getDefaultEnum()
    {
        $o = $this->__offset(74);
        return $o != 0 ? $this->bb->getSbyte($o + $this->bb_pos) : \optional_scalars\OptionalByte::One;
    }

    /**
     * @param FlatBufferBuilder $builder
     * @return void
     */
    public static function startScalarStuff(FlatBufferBuilder $builder)
    {
        $builder->StartObject(36);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @return ScalarStuff
     */
    public static function createScalarStuff(FlatBufferBuilder $builder, $just_i8, $maybe_i8, $default_i8, $just_u8, $maybe_u8, $default_u8, $just_i16, $maybe_i16, $default_i16, $just_u16, $maybe_u16, $default_u16, $just_i32, $maybe_i32, $default_i32, $just_u32, $maybe_u32, $default_u32, $just_i64, $maybe_i64, $default_i64, $just_u64, $maybe_u64, $default_u64, $just_f32, $maybe_f32, $default_f32, $just_f64, $maybe_f64, $default_f64, $just_bool, $maybe_bool, $default_bool, $just_enum, $maybe_enum, $default_enum)
    {
        $builder->startObject(36);
        self::addJustI8($builder, $just_i8);
        self::addMaybeI8($builder, $maybe_i8);
        self::addDefaultI8($builder, $default_i8);
        self::addJustU8($builder, $just_u8);
        self::addMaybeU8($builder, $maybe_u8);
        self::addDefaultU8($builder, $default_u8);
        self::addJustI16($builder, $just_i16);
        self::addMaybeI16($builder, $maybe_i16);
        self::addDefaultI16($builder, $default_i16);
        self::addJustU16($builder, $just_u16);
        self::addMaybeU16($builder, $maybe_u16);
        self::addDefaultU16($builder, $default_u16);
        self::addJustI32($builder, $just_i32);
        self::addMaybeI32($builder, $maybe_i32);
        self::addDefaultI32($builder, $default_i32);
        self::addJustU32($builder, $just_u32);
        self::addMaybeU32($builder, $maybe_u32);
        self::addDefaultU32($builder, $default_u32);
        self::addJustI64($builder, $just_i64);
        self::addMaybeI64($builder, $maybe_i64);
        self::addDefaultI64($builder, $default_i64);
        self::addJustU64($builder, $just_u64);
        self::addMaybeU64($builder, $maybe_u64);
        self::addDefaultU64($builder, $default_u64);
        self::addJustF32($builder, $just_f32);
        self::addMaybeF32($builder, $maybe_f32);
        self::addDefaultF32($builder, $default_f32);
        self::addJustF64($builder, $just_f64);
        self::addMaybeF64($builder, $maybe_f64);
        self::addDefaultF64($builder, $default_f64);
        self::addJustBool($builder, $just_bool);
        self::addMaybeBool($builder, $maybe_bool);
        self::addDefaultBool($builder, $default_bool);
        self::addJustEnum($builder, $just_enum);
        self::addMaybeEnum($builder, $maybe_enum);
        self::addDefaultEnum($builder, $default_enum);
        $o = $builder->endObject();
        return $o;
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param sbyte
     * @return void
     */
    public static function addJustI8(FlatBufferBuilder $builder, $justI8)
    {
        $builder->addSbyteX(0, $justI8, 0);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param sbyte
     * @return void
     */
    public static function addMaybeI8(FlatBufferBuilder $builder, $maybeI8)
    {
        $builder->addSbyteX(1, $maybeI8, null);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param sbyte
     * @return void
     */
    public static function addDefaultI8(FlatBufferBuilder $builder, $defaultI8)
    {
        $builder->addSbyteX(2, $defaultI8, 42);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param byte
     * @return void
     */
    public static function addJustU8(FlatBufferBuilder $builder, $justU8)
    {
        $builder->addByteX(3, $justU8, 0);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param byte
     * @return void
     */
    public static function addMaybeU8(FlatBufferBuilder $builder, $maybeU8)
    {
        $builder->addByteX(4, $maybeU8, null);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param byte
     * @return void
     */
    public static function addDefaultU8(FlatBufferBuilder $builder, $defaultU8)
    {
        $builder->addByteX(5, $defaultU8, 42);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param short
     * @return void
     */
    public static function addJustI16(FlatBufferBuilder $builder, $justI16)
    {
        $builder->addShortX(6, $justI16, 0);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param short
     * @return void
     */
    public static function addMaybeI16(FlatBufferBuilder $builder, $maybeI16)
    {
        $builder->addShortX(7, $maybeI16, null);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param short
     * @return void
     */
    public static function addDefaultI16(FlatBufferBuilder $builder, $defaultI16)
    {
        $builder->addShortX(8, $defaultI16, 42);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param ushort
     * @return void
     */
    public static function addJustU16(FlatBufferBuilder $builder, $justU16)
    {
        $builder->addUshortX(9, $justU16, 0);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param ushort
     * @return void
     */
    public static function addMaybeU16(FlatBufferBuilder $builder, $maybeU16)
    {
        $builder->addUshortX(10, $maybeU16, null);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param ushort
     * @return void
     */
    public static function addDefaultU16(FlatBufferBuilder $builder, $defaultU16)
    {
        $builder->addUshortX(11, $defaultU16, 42);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param int
     * @return void
     */
    public static function addJustI32(FlatBufferBuilder $builder, $justI32)
    {
        $builder->addIntX(12, $justI32, 0);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param int
     * @return void
     */
    public static function addMaybeI32(FlatBufferBuilder $builder, $maybeI32)
    {
        $builder->addIntX(13, $maybeI32, null);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param int
     * @return void
     */
    public static function addDefaultI32(FlatBufferBuilder $builder, $defaultI32)
    {
        $builder->addIntX(14, $defaultI32, 42);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param uint
     * @return void
     */
    public static function addJustU32(FlatBufferBuilder $builder, $justU32)
    {
        $builder->addUintX(15, $justU32, 0);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param uint
     * @return void
     */
    public static function addMaybeU32(FlatBufferBuilder $builder, $maybeU32)
    {
        $builder->addUintX(16, $maybeU32, null);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param uint
     * @return void
     */
    public static function addDefaultU32(FlatBufferBuilder $builder, $defaultU32)
    {
        $builder->addUintX(17, $defaultU32, 42);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param long
     * @return void
     */
    public static function addJustI64(FlatBufferBuilder $builder, $justI64)
    {
        $builder->addLongX(18, $justI64, 0);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param long
     * @return void
     */
    public static function addMaybeI64(FlatBufferBuilder $builder, $maybeI64)
    {
        $builder->addLongX(19, $maybeI64, null);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param long
     * @return void
     */
    public static function addDefaultI64(FlatBufferBuilder $builder, $defaultI64)
    {
        $builder->addLongX(20, $defaultI64, 42);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param ulong
     * @return void
     */
    public static function addJustU64(FlatBufferBuilder $builder, $justU64)
    {
        $builder->addUlongX(21, $justU64, 0);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param ulong
     * @return void
     */
    public static function addMaybeU64(FlatBufferBuilder $builder, $maybeU64)
    {
        $builder->addUlongX(22, $maybeU64, null);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param ulong
     * @return void
     */
    public static function addDefaultU64(FlatBufferBuilder $builder, $defaultU64)
    {
        $builder->addUlongX(23, $defaultU64, 42);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param float
     * @return void
     */
    public static function addJustF32(FlatBufferBuilder $builder, $justF32)
    {
        $builder->addFloatX(24, $justF32, 0.0);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param float
     * @return void
     */
    public static function addMaybeF32(FlatBufferBuilder $builder, $maybeF32)
    {
        $builder->addFloatX(25, $maybeF32, null);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param float
     * @return void
     */
    public static function addDefaultF32(FlatBufferBuilder $builder, $defaultF32)
    {
        $builder->addFloatX(26, $defaultF32, 42.0);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param double
     * @return void
     */
    public static function addJustF64(FlatBufferBuilder $builder, $justF64)
    {
        $builder->addDoubleX(27, $justF64, 0.0);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param double
     * @return void
     */
    public static function addMaybeF64(FlatBufferBuilder $builder, $maybeF64)
    {
        $builder->addDoubleX(28, $maybeF64, null);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param double
     * @return void
     */
    public static function addDefaultF64(FlatBufferBuilder $builder, $defaultF64)
    {
        $builder->addDoubleX(29, $defaultF64, 42.0);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param bool
     * @return void
     */
    public static function addJustBool(FlatBufferBuilder $builder, $justBool)
    {
        $builder->addBoolX(30, $justBool, false);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param bool
     * @return void
     */
    public static function addMaybeBool(FlatBufferBuilder $builder, $maybeBool)
    {
        $builder->addBoolX(31, $maybeBool, false);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param bool
     * @return void
     */
    public static function addDefaultBool(FlatBufferBuilder $builder, $defaultBool)
    {
        $builder->addBoolX(32, $defaultBool, false);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param sbyte
     * @return void
     */
    public static function addJustEnum(FlatBufferBuilder $builder, $justEnum)
    {
        $builder->addSbyteX(33, $justEnum, 0);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param sbyte
     * @return void
     */
    public static function addMaybeEnum(FlatBufferBuilder $builder, $maybeEnum)
    {
        $builder->addSbyteX(34, $maybeEnum, null);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param sbyte
     * @return void
     */
    public static function addDefaultEnum(FlatBufferBuilder $builder, $defaultEnum)
    {
        $builder->addSbyteX(35, $defaultEnum, 1);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @return int table offset
     */
    public static function endScalarStuff(FlatBufferBuilder $builder)
    {
        $o = $builder->endObject();
        return $o;
    }

    public static function finishScalarStuffBuffer(FlatBufferBuilder $builder, $offset)
    {
        $builder->finish($offset, "NULL");
    }

    public static function finishSizePrefixedScalarStuffBuffer(FlatBufferBuilder $builder, $offset)
    {
        $builder->finish($offset, "NULL", true);
    }
}
