<?php
// automatically generated by the FlatBuffers compiler, do not modify

use \Google\FlatBuffers\Struct;
use \Google\FlatBuffers\Table;
use \Google\FlatBuffers\ByteBuffer;
use \Google\FlatBuffers\FlatBufferBuilder;
use \Google\FlatBuffers\Constants;
use \Google\FlatBuffers\IUnpackableObject;
use \Google\FlatBuffers\IGeneratedObject;

class MovieT implements IGeneratedObject
{
    /**
     * @var CharacterT $main_character
     */
    public $main_character;

    /**
     * @var CharacterT $characters_type
     */
    public $characters_type;

    /**
     * @var CharacterT $characters
     */
    public $characters;

    /**
     * @param CharacterT $main_character
     * @param CharacterT $characters_type
     * @param CharacterT $characters
     */
    public function __construct($main_character = null, $characters_type = null, $characters = null)
    {
        $this->main_character = $main_character;
        $this->characters_type = $characters_type;
        $this->characters = $characters;
    }

    /**
     * @param FlatBufferBuilder $builder
     * @return int offset
     */
    public function pack(FlatBufferBuilder $builder)
    {
        if ($this->main_character !== null && $this->main_character->value !== null) {
            $main_character = $this->main_character->value->pack($builder);
        }
        if ($this->characters_type !== null) {
            $characters_type = Movie::createCharactersTypeVector($builder, $this->characters_type);
        }
        if ($this->characters !== null) {
            $characters = Movie::createCharactersVector($builder, $this->characters);
        }
        Movie::startMovie($builder);
        if ($this->main_character !== null && $this->main_character->type !== null) {
            Movie::addMainCharacterType($builder, $this->main_character->type);
            Movie::addMainCharacter($builder, $main_character);
        }
        if ($this->characters_type !== null) {
            Movie::addCharactersType($builder, $characters_type);
        }
        if ($this->characters !== null) {
            Movie::addCharacters($builder, $characters);
        }
        $movie = Movie::endMovie($builder);
        return $movie;
    }
}

class Movie extends Table implements IUnpackableObject
{
    /**
     * @param ByteBuffer $bb
     * @return Movie
     */
    public static function getRootAsMovie(ByteBuffer $bb)
    {
        $obj = new Movie();
        return $obj->init($bb->getInt($bb->getPosition()) + $bb->getPosition(), $bb);
    }

    /**
     * @param ByteBuffer $bb
     * @return Movie
     */
    public static function getSizePrefixedRootAsMovie(ByteBuffer $bb)
    {
        $obj = new Movie();
        $bb->setPosition($bb->getPosition() + Constants::SIZEOF_INT);
        return $obj->init($bb->getInt($bb->getPosition()) + $bb->getPosition(), $bb);
    }

    public static function MovieIdentifier()
    {
        return "MOVI";
    }

    public static function MovieBufferHasIdentifier(ByteBuffer $buf)
    {
        return self::__has_identifier($buf, self::MovieIdentifier());
    }

    /**
     * @param int $_i offset
     * @param ByteBuffer $_bb
     * @return Movie
     **/
    public function init($_i, ByteBuffer $_bb)
    {
        $this->bb_pos = $_i;
        $this->bb = $_bb;
        return $this;
    }

    /**
     * @return byte
     */
    public function getMainCharacterType()
    {
        $o = $this->__offset(4);
        return $o != 0 ? $this->bb->getByte($o + $this->bb_pos) : \Character::NONE;
    }

    /**
     * @return int
     */
    public function getMainCharacter($obj)
    {
        $o = $this->__offset(6);
        return $o != 0 ? $this->__union($obj, $o) : null;
    }

    /**
     * @param int offset
     * @return byte
     */
    public function getCharactersType($j)
    {
        $o = $this->__offset(8);
        return $o != 0 ? $this->bb->getByte($this->__vector($o) + $j * 1) : \Character::NONE;
    }

    /**
     * @return int
     */
    public function getCharactersTypeLength()
    {
        $o = $this->__offset(8);
        return $o != 0 ? $this->__vector_len($o) : 0;
    }

    /**
     * @param int offset
     * @return Table
     */
    public function getCharacters($j, $obj)
    {
        $o = $this->__offset(10);
        return $o != 0 ? $this->__union($obj, $this->__vector($o) + $j * 4 - $this->bb_pos) : null;
    }

    /**
     * @return int
     */
    public function getCharactersLength()
    {
        $o = $this->__offset(10);
        return $o != 0 ? $this->__vector_len($o) : 0;
    }

    /**
     * @param FlatBufferBuilder $builder
     * @return void
     */
    public static function startMovie(FlatBufferBuilder $builder)
    {
        $builder->startObject(4);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @return Movie
     */
    public static function createMovie(FlatBufferBuilder $builder, $main_character_type, $main_character, $characters_type, $characters)
    {
        $builder->startObject(4);
        self::addMainCharacterType($builder, $main_character_type);
        self::addMainCharacter($builder, $main_character);
        self::addCharactersType($builder, $characters_type);
        self::addCharacters($builder, $characters);
        $o = $builder->endObject();
        return $o;
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param byte
     * @return void
     */
    public static function addMainCharacterType(FlatBufferBuilder $builder, $mainCharacterType)
    {
        $builder->addByteX(0, $mainCharacterType, \Character::NONE);
    }

    public static function addMainCharacter(FlatBufferBuilder $builder, $offset)
    {
        $builder->addOffsetX(1, $offset, 0);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param VectorOffset
     * @return void
     */
    public static function addCharactersType(FlatBufferBuilder $builder, $charactersType)
    {
        $builder->addOffsetX(2, $charactersType, \Character::NONE);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param array offset array
     * @return int vector offset
     */
    public static function createCharactersTypeVector(FlatBufferBuilder $builder, array $data)
    {
        $builder->startVector(1, count($data), 1);
        for ($i = count($data) - 1; $i >= 0; $i--) {
            $builder->putByte($data[$i]);
        }
        return $builder->endVector();
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param int $numElems
     * @return void
     */
    public static function startCharactersTypeVector(FlatBufferBuilder $builder, $numElems)
    {
        $builder->startVector(1, $numElems, 1);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param VectorOffset
     * @return void
     */
    public static function addCharacters(FlatBufferBuilder $builder, $characters)
    {
        $builder->addOffsetX(3, $characters, \Character::NONE);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param array offset array
     * @return int vector offset
     */
    public static function createCharactersVector(FlatBufferBuilder $builder, array $data)
    {
        $builder->startVector(4, count($data), 4);
        for ($i = count($data) - 1; $i >= 0; $i--) {
            $builder->putOffset($data[$i]);
        }
        return $builder->endVector();
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param int $numElems
     * @return void
     */
    public static function startCharactersVector(FlatBufferBuilder $builder, $numElems)
    {
        $builder->startVector(4, $numElems, 4);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @return int table offset
     */
    public static function endMovie(FlatBufferBuilder $builder)
    {
        $o = $builder->endObject();
        return $o;
    }

    public static function finishMovieBuffer(FlatBufferBuilder $builder, $offset)
    {
        $builder->finish($offset, "MOVI");
    }

    public static function finishSizePrefixedMovieBuffer(FlatBufferBuilder $builder, $offset)
    {
        $builder->finish($offset, "MOVI", true);
    }

    /**
     * @param MovieT $o
     */
    public function unPackTo(&$o)
    {
        $main_character = $this->getMainCharacterType();
        if ($main_character !== null) {
            $o->main_character = Character::unPack($main_character, array($this, 'getMainCharacter'));
        }
        $o->characters_type = array();
        $characters_type_len = $this->getCharactersTypeLength();
        for ($i = 0; $i < $characters_type_len; $i++) {
            array_push($o->characters_type, $this->getCharactersType($i));
        }
        $o->characters = array();
        $characters_len = $this->getCharactersLength();
        for ($i = 0; $i < $characters_len; $i++) {
            array_push($o->characters, $this->getCharacters($i));
        }
    }

    /**
     * @return MovieT
     */
    public function unPack()
    {
        $o = new MovieT();
        $this->unPackTo($o);
        return $o;
    }
}
