<?php
// automatically generated by the FlatBuffers compiler, do not modify

use \Google\FlatBuffers\Struct;
use \Google\FlatBuffers\Table;
use \Google\FlatBuffers\ByteBuffer;
use \Google\FlatBuffers\FlatBufferBuilder;
use \Google\FlatBuffers\Constants;
use \Google\FlatBuffers\IUnpackableObject;
use \Google\FlatBuffers\IGeneratedObject;

class RapunzelT implements IGeneratedObject
{
    /**
     * @var int $hair_length
     */
    public $hair_length;

    /**
     * @param int $hair_length
     */
    public function __construct($hair_length = 0)
    {
        $this->hair_length = $hair_length;
    }

    /**
     * @param FlatBufferBuilder $builder
     * @return int offset
     */
    public function pack(FlatBufferBuilder $builder)
    {
        return Rapunzel::createRapunzel($builder, $this->hairLength);
    }
}

class Rapunzel extends Struct implements IUnpackableObject
{
    /**
     * @param int $_i offset
     * @param ByteBuffer $_bb
     * @return Rapunzel
     **/
    public function init($_i, ByteBuffer $_bb)
    {
        $this->bb_pos = $_i;
        $this->bb = $_bb;
        return $this;
    }

    /**
     * @return int
     */
    public function GetHairLength()
    {
        return $this->bb->getInt($this->bb_pos + 0);
    }


    /**
     * @return int offset
     */
    public static function createRapunzel(FlatBufferBuilder $builder, $hairLength)
    {
        $builder->prep(4, 4);
        $builder->putInt($hairLength);
        return $builder->offset();
    }

    /**
     * @param RapunzelT $o
     */
    public function unPackTo(&$o)
    {
        $o->hair_length = $this->GetHairLength();
    }

    /**
     * @return RapunzelT
     */
    public function unPack()
    {
        $o = new RapunzelT();
        $this->unPackTo($o);
        return $o;
    }
}
